[versions]
spring-kafka                                = "3.0.4"
spring-boot                                 = "3.1.1"
spring-dependency-management                = "1.1.0"
reactor                                     = "3.5.7"
hibernate-validator                         = "8.0.1.Final"
commons-lang3                               = "3.12.0"
reactor-kafka                               = "1.3.18"

[libraries]
spring-boot-starter                         = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-web                     = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-actuator                = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-webflux                 = { module = "org.springframework.boot:spring-boot-starter-webflux" }
spring-kafka                                = { module = "org.springframework.kafka:spring-kafka", version.ref = "spring-kafka"}
reactor                                     = { module = "io.projectreactor:reactor-core", version.ref = "reactor" }
hibernate-validator                         = { module = "org.hibernate.validator:hibernate-validator", version.ref = "hibernate-validator" }
commons-lang3                               = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
reactor-kafka                               = { module = "io.projectreactor.kafka:reactor-kafka", version.ref = "reactor-kafka" }

[plugins]
spring-boot                                 = { id = "org.springframework.boot", version.ref = "spring-boot"}
spring-dependency-management                = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management"}