[versions]
assertj                = "3.24.2"
junit                  = "5.10.0"
rest-assured           = "5.3.0"
spring-kafka-test      = "3.0.8"

[libraries]
assertj-core                        = { module = "org.assertj:assertj-core", version.ref = "assertj" }
spring-boot-starter-test            = { module = "org.springframework.boot:spring-boot-starter-test" }
junit-jupiter-api                   = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
reactor-test                        = { module= "io.projectreactor:reactor-test" }
rest-assured                        = { module = "io.rest-assured:rest-assured", version.ref ="rest-assured" }
spring-kafka-test                   = { module = "org.springframework.kafka:spring-kafka-test", version.ref ="spring-kafka-test" }
